apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-reloader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.name }}-reloader
rules:
- apiGroups: ['', '*']
  resources: ["deployments", "configmaps"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}-reloader
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}-reloader
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Values.name }}-reloader
  apiGroup: rbac.authorization.k8s.io
