apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-auto-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.name }}-auto-config
rules:
- apiGroups: ['', '*']
  resources: ["configmaps"]
  verbs:
    - get
    - list
    - create
    - update
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}-auto-config
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}-auto-config
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Values.name }}-auto-config
  apiGroup: rbac.authorization.k8s.io
