{{- if .Values.reloader.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name {{ .Values.name }}-reloader
  labels:
    app.kubernetes.io/name: *name
spec:
  replicas: {{ .Values.reloader.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: *name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: *name
    spec:
      serviceAccountName: {{ .Values.name }}-reloader
      volumes:
        - name: bin
          configMap:
            name: {{ .Values.name }}-bin
            defaultMode: 0755
      containers:
        - name: reloader
          image: registry.gitlab.ics.muni.cz:443/cloud/g2/container-registry/docker.io__ubuntu:jammy
          command: ["/tmp/reloader.sh"]
          volumeMounts:
            - name: bin
              mountPath: /tmp/reloader.sh
              subPath: reloader.sh
              readOnly: true
            - name: bin
              mountPath: /tmp/transcribe-mapping.py
              subPath: transcribe-mapping.py
              readOnly: true
          env:
          - name: OS_AUTH_URL
            value: {{ .Values.cloudkeeper_os.config.keystone_authtoken.auth_url | quote }}
          - name: OS_USERNAME
            value: {{ .Values.cloudkeeper_os.config.keystone_authtoken.username | quote }}
          - name: OS_PASSWORD
{{- if .Values.cloudkeeper.enabled }}
            valueFrom:
              secretKeyRef:
                key: cloudkeeper_user_password
                name: {{ .Values.name }}-cloudkeeper-user
{{- else }}
            value: {{ .Values.cloudkeeper_os.config.keystone_authtoken.password | quote }}
{{- end }}
{{- if .Values.cloudkeeper_os.config.keystone_authtoken.project_domain_name }}
          - name: OS_PROJECT_DOMAIN_NAME
            value: {{ .Values.cloudkeeper_os.config.keystone_authtoken.project_domain_name | quote }}
{{- end }}
{{- if .Values.cloudkeeper_os.config.keystone_authtoken.project_domain_name }}
          - name: OS_USER_DOMAIN_NAME
            value: {{ .Values.cloudkeeper_os.config.keystone_authtoken.user_domain_name | quote }}
{{- end }}
{{- if .Values.cloudkeeper_os.config.keystone_authtoken.project_name }}
          - name: OS_PROJECT_NAME
            value: {{ .Values.cloudkeeper_os.config.keystone_authtoken.project_name | quote }}
{{- end }}
{{- end }}
