{{- if .Values.cloudkeeper.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-cloudkeeper-user
stringData:
  cloudkeeper_user_password: {{ .Values.cloudkeeper_os.config.keystone_authtoken.password | quote }}
{{- end }}
