{{- if .Values.cloudkeeper.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-cloudkeeper-user
stringData:
  OS_AUTH_URL: {{ .Values.users.OS_AUTH_URL | quote }}
  OS_REGION_NAME: {{ .Values.users.OS_REGION_NAME | quote }}
  OS_INTERFACE: "internal"
  OS_PROJECT_DOMAIN_NAME: "default"
  OS_PROJECT_NAME: "admin"
  OS_USER_DOMAIN_NAME: "default"
  OS_USERNAME: "cloudkeeper"
  OS_PASSWORD: {{ .Values.users.cloudkeeperPassword | quote }}
  OS_DEFAULT_DOMAIN: "default"
{{- end }}
