apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-etc
data:

{{- if .Values.caso.enabled }}

  caso.conf: |
    [DEFAULT]
    {{- range $key, $val := .Values.caso.config.DEFAULT }}
    {{ $key }} = {{ $val }}
    {{- end }}

    [keystone_auth]
    {{- range $key, $val := .Values.caso.config.keystone_auth }}
    {{ $key }} = {{ $val }}
    {{- end }}

{{- if .Values.caso.voms }}
  voms.json: |
    {{ .Values.caso.voms | toYaml | fromYaml | toJson }}
{{- end }}
{{- end }}

{{- if .Values.ssm.enabled }}
  sender.cfg: |
    [sender]
    {{- toYaml .Values.ssm.config.sender | nindent 4 }}

    [broker]
    {{- toYaml .Values.ssm.config.broker | nindent 4 }}

    [certificates]
    {{- toYaml .Values.ssm.config.certificates | nindent 4 }}

    [messaging]
    {{- toYaml .Values.ssm.config.messaging | nindent 4 }}

    [logging]
    {{- toYaml .Values.ssm.config.logging | nindent 4 }}
{{- end }}
