{{- if .Values.ssm.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name }}-ssm
spec:
  schedule: {{ .Values.ssm.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .Values.name }}-ssm
        spec:
          volumes:
            - name: config
              configMap:
                name: {{ .Values.name }}-etc
            - name: accounting
              persistentVolumeClaim:
                claimName: {{ .Values.name }}
            - name: certs
              secret:
                secretName: {{ .Values.name }}-ssm-certs
          containers:
            - name: ssm
              image: {{ .Values.ssm.image }}:{{ .Values.ssm.tag }}
              volumeMounts:
              - name: config
                mountPath: /etc/apel/sender.cfg
                subPath: sender.cfg
                readOnly: true
              - name: accounting
                mountPath: /var/spool/apel
                readOnly: true
              - name: certs
                mountPath: /etc/grid-security/hostcert.pem
                subPath: grid_security_cert
                readOnly: true
              - name: certs
                mountPath: /etc/grid-security/hostkey.pem
                subPath: grid_security_key
                readOnly: true
          restartPolicy: OnFailure
{{- if .Values.ssm.hostAliases }}
          hostAliases:
{{- toYaml .Values.ssm.hostAliases | nindent 12 }}
{{- end }}
{{- if .Values.ssm.affinity }}
          affinity:
{{- toYaml .Values.ssm.affinity | nindent 12 }}
{{- end }}
{{- end }}
