{{- if .Values.caso.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.name }}-caso
spec:
  schedule: {{ .Values.caso.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .Values.name }}-caso
        spec:
          volumes:
            - name: config
              configMap:
                name: {{ .Values.name }}-etc
            - name: accounting
              persistentVolumeClaim:
                claimName: {{ .Values.name }}
          containers:
            - name: caso
              image: {{ .Values.caso.image }}:{{ .Values.caso.tag }}
              volumeMounts:
              - name: config
                mountPath: /etc/caso/caso.conf
                subPath: caso.conf
                readOnly: true
{{- if .Values.caso.voms }}
              - name: config
                mountPath: /etc/caso/voms.json
                subPath: voms.json
                readOnly: true
{{- end }}
              - name: accounting
                mountPath: /var/spool/apel
          restartPolicy: OnFailure
          affinity:
            podAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 50
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                      - {{ .Values.name }}-ssm
                  topologyKey: kubernetes.io/hostname
{{- end }}
