{{- if .Values.ssm.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-ssm-certs
stringData:
  grid_security_cert: {{ .Values.ssm.certs.grid_security_cert | quote }}
  grid_security_key: {{ .Values.ssm.certs.grid_security_key | quote }}
{{- end }}
