apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Release.Name }}-db-backup-cronjob"
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            env:
            - name: MARIADB_HOST_NAME
              value: "{{ .Values.config.mariadbHostName }}"
            - name: S3_HOST
              value: "{{ .Values.config.s3Host }}"
            - name: S3_PORT
              value: "{{ .Values.config.s3Port }}"
            - name: S3_ACCESS_KEY_ID
              value: "{{ .Values.config.s3AccessKeyId }}"
            - name: S3_SECRET_ACCESS_KEY
              value: "{{ .Values.config.s3SecretAccessKey }}"
            - name: S3_BACKUP_PATH
              value: "{{ .Values.config.s3BackupPath }}"
            - name: MARIADB_USER
              value: "{{ .Values.config.mariadbUser }}"
            - name: MARIADB_PASSWORD
              value: "{{ .Values.config.mariadbPassword }}"
            - name: MARIADB_HOST
              value: "{{ .Values.config.mariadbHost }}"
            - name: MARIADB_PORT
              value: "{{ .Values.config.mariadbPort }}"
            - name: MARIADB_DBS
              value: "{{ .Values.config.mariadbDbs }}"
          restartPolicy: OnFailure

