{{- if .Values.manifests.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
stringData:
  ESACO_USER_PASSWORD: {{ .Values.configuration.env_vars.ESACO_USER_PASSWORD }}
  application.yml: |
{{- with . -}}
{{- $templateRendered := tpl ( .Values.configuration.oidc_providers | toYaml ) . }}
{{- if hasPrefix "|\n" $templateRendered }}
{{ $templateRendered | trimPrefix "|\n" | indent 2 }}
{{- else }}
{{ $templateRendered | indent 2 }}
{{- end -}}
{{- end -}}

{{- end }}
