apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: &app rook-ceph-cluster-config
  name: &app-job "{{ .Values.jobs.cleanup.name }}"
  annotations:
    "helm.sh/hook": pre-delete
spec:
  template:
    metadata:
      labels:
        app: *app
        job-name: *app-job
    spec:
      containers:
      - name: *app-job
        command:
        - &script-path /tmp/rook-ceph-cluster-config-cleanup.sh
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        volumeMounts:
        - mountPath: *script-path
          name: "{{ .Values.configmaps.internal.scripts.name }}"
          readOnly: true
          subPath: rook-ceph-cluster-config-cleanup.sh
      restartPolicy: OnFailure
      serviceAccount: {{ .Values.serviceAccount.name }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
      - configMap:
          defaultMode: 365
          name: "{{ .Values.configmaps.internal.scripts.name }}"
        name: "{{ .Values.configmaps.internal.scripts.name }}"
