name: egi-appliances

users:
  init: true
  OS_AUTH_URL: http://keystone-api.openstack.svc.cluster.local:5000/v3
  OS_REGION_NAME: "default"
  adminProjectID: ""
  cloudkeeperPassword: ""
  init_keystone_user_secret_name: ""

persistence: # TODO: refactor if really needed
  storageClass: default
  size: 30Gi

cloudkeeper:
  enabled: true
  schedule: "0 */4 * * *"
  image: egifedcloud/cloudkeeper
  tag: v0.16
  mapping:
    name: ""                                           # Used for extraction of vos and projects
    exclude_projects: '"{0}", "admin"'
    domain_name: ""
  image_list_token:                                    # etc/cloudkeeper/image-lists.conf
  config:
    image-lists-file: /etc/cloudkeeper/image-lists.conf
    ca-dir: /etc/grid-security/certificates/           # CA directory
    authentication: false                              # core (client) <-> backend (server) authentication (certificate, key and backend-certificate options)
    certificate: /etc/grid-security/hostcert.pem       # Core's host certificate
    key: /etc/grid-security/hostkey.pem                # Core's host key
    image-dir: /var/spool/cloudkeeper/images/          # Directory to store images to
    external-tools:
      binaries:
        qemu-img: /usr/bin/qemu-img                    # qemu-img binary (image conversion) location
        nginx: /usr/bin/nginx                          # nginx binary (HTTP server) location
      execution-timeout: 600                           # timeout for execution of external tools in seconds
    remote-mode: false                                 # Remote mode starts HTTP server (NGINX) and serves images to backend via HTTP
    nginx:
      runtime-dir: /var/run/cloudkeeper/               # Runtime directory for NGINX
      error-log-file: /var/log/cloudkeeper/nginx-error.log # File for NGINX error log
      access-log-file: /var/log/cloudkeeper/nginx-access.log # File for NGINX access log
      pid-file: /var/run/cloudkeeper/nginx.pid         # NGINX pid file
      ip-address: 127.0.0.1                            # IP address NGINX can listen on
      port: 50505                                      # Port NGINX can listen on
      proxy:
        ip-address: ""                                 # Proxy IP address
        port: ""                                       # Proxy port
        ssl: false                                     # Whether proxy will use SSL connection
    backend:
      endpoint: 127.0.0.1:50051                        # Backend's gRPC endpoint
      certificate: /etc/grid-security/backendcert.pem  # Backend's certificate
    formats:                                           # List of acceptable formats images can be converted to
      - qcow2
    logging:
      level: ERROR                                     # Logging level
      file: /var/log/cloudkeeper/cloudkeeper.log       # File to write log to. To turn off file logging leave this field empty.
    debug: false                                       # Debug mode
    lock-file: /var/lock/cloudkeeper/cloudkeeper.lock  # File used to ensure only one running instance of cloudkeeper

cloudkeeper_os:
  enabled: true
  replicas: 1
  image: egifedcloud/cloudkeeper-os
  tag: v0.16
  config:                                              # https://github.com/enolfc/fedcloudappliance/blob/master/cloudkeeper/os/cloudkeeper-os.conf
    DEFAULT: {}
    keystone_authtoken:
      auth_url: http://keystone-api.openstack.svc.cluster.local:5000/v3  # ostack endpoint
      username: ""                                     # cloudkeeper ostack user
      password: ""                                     # cloudkeeper ostack user's pass
      #user_domain_name: egi_eu
      #project_domain_name: egi_eu

reloader:
  enabled: true
  replicas: 1
  interval: 10m
