{{- if .Values.manifests.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  {{- if .Values.service.loadBalancerIP.enabled }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP.ip }}
  allocateLoadBalancerNodePorts: {{ .Values.service.loadBalancerIP.allocateLoadBalancerNodePorts }}
  {{- end }}
  {{ if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{ end }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  - port: 443
    protocol: TCP
    targetPort: 443
    name: https
  selector:
    {{- toYaml .Values.service.selector | nindent 4 }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
{{- end }}
